### ISSUE TITLE
Add custom user agent to each container

### ISSUE THREAD

**Issue by Iquaridys** [bekh6ex/firefox-container-proxy#14]
Add custom user agent each container,
will be great if generate random fingerprint like canvas each container

**Comment by bekh6ex** [comment]
Great idea. Goes a bit beyond extension purpose but in the same way.

It would be awesome if someone would think it through:

- How to do it technically?
- Just set up for each container or generate it randomly?

**Comment by Iquaridys** [comment]
- like how to use a proxy. Can be made a new place or shared with a proxy, there are 2 options real agent (default) or user agent input from the user
- set by the user himself because it's easy to find a list of user agents

**Comment by ImCowboySibs** [comment]
You Can generate a Unique Fingerprint per container with the CanvasBlocker Extension, but cannot set a specific UA per user Container. 

There is a Stack thread over this same function which may assist in this implementation. [https://stackoverflow.com/questions/22361720/how-can-i-change-the-user-agent-in-just-one-tab-of-firefox](url)

**Comment by Yoskaldyr** [comment]
It will be good if some options of this addon will be added:
https://github.com/sereneblue/chameleon

**Comment by bekh6ex** [comment]
I see the value, but I don't have any capacity to add this functionality.
Also, it's not the purpose of this addon, so the new one should be created.

If there are volounteers to start it, I can help with an advice :)
