### ISSUE TITLE
Won't connect through SmartProxy

### ISSUE THREAD

**Issue by ndmgrphc** [bekh6ex/firefox-container-proxy#18]
Not sure if I'm missing something but I'm curious why it won't work through SmartProxy.io proxies.  I've tried a number of configurations but get a connection error during testing.  

The smartproxy connections are fine with firefox direct settings: https://help.smartproxy.com/docs/how-to-setup-proxy-on-firefox-browser

**Comment by ndmgrphc** [comment]
Optionally, could you provide a list of requirements for proxies that will work?  Protocol, etc?

**Comment by bekh6ex** [comment]
There was an issue with DuckDuckGo regarding IP extraction, might be related to it. See https://www.reddit.com/r/duckduckgo/comments/ehe6ok/what_happened_to_my_ip_instant_answer/

Regarding requirements. The same as for Firefox, currently: HTTP, HTTPS, SOCKS5(SOCKS) and SOCKS4.

This addon does not do any logic, except telling Firefox which settings to use.

**Comment by bekh6ex** [comment]
I guess it was related to Duckduckgo issue.
