### ISSUE TITLE
IP whitelist for specific proxies

### ISSUE THREAD

**Issue by fishnux** [bekh6ex/firefox-container-proxy#21]
Hi,

I need to allow a specific IP address (localhost/127.0.0.1) to bypass a proxy, like what happens when you manually configure a proxy on Firefox. Would it be possible to add a whitelist on the extension's proxy configuration page?

Thanks!

**Comment by bug-repport** [comment]
Yes, me too! Trezor connection 127.0.0.1

![2020-05-18_015553](https://user-images.githubusercontent.com/59339852/82162143-ccb03000-9891-11ea-833a-22c3a9809e48.png)

**Comment by bekh6ex** [comment]
I'm wondering what would be the simplest useful solution to not overload the interface?

I would suggest to just add a one list for all the proxies as a general setting and fill it with safe defaults (e.g. 127.0.0.1, localhost, ::1). 

Would it be sufficient? What do you think?

**PS**: Don't see a reason to set it up for each proxy. Why would one proxy have different setting than other?
If anything, I think it might make sense to set it up per container, but then the interface would need a redesign and I'm not sure how useful this feature would be.

**Comment by fishnux** [comment]
For me that would work, a whitelist as a general setting 👍

**Comment by bug-repport** [comment]
127.0.0.1 that's enough for me!

**Comment by bug-repport** [comment]
how soon will you update the plugin?

**Comment by bekh6ex** [comment]
Sadly, cannot promise anything these days. Too many things on my plate.

If someone creates a pull request with the fix, I might be able to merge and release it rather quickly.

**Comment by bug-repport** [comment]
Куда тебе можно задонейтить за реализацию этой функции?

**Comment by bekh6ex** [comment]
Finally, I've managed to fix this.
There is no configuration needed. The extension replicates Firefox behaviour and will not proxy any request from any container directed to `localhost`,  `127.0.0.1` or `::1`.

Update to extension version 0.1.14
