### ISSUE TITLE
[Request] Add SSH Tunnel in proxy

### ISSUE THREAD

**Issue by thienha1** [bekh6ex/firefox-container-proxy#26]
Can you make it work with SSH Tunnel, also test it after save?

**Comment by thienha1** [comment]
But I can't using SSH per tab like this, multiple running ssh just to run proxy SOCKS5

**Comment by nobodysu** [comment]
? This scheme supports multiple instances - just change the local port [and socks file].

**Comment by bekh6ex** [comment]
To be honest I'm not 100% sure what is meant here.
If you want FF to establish SSH tunnel as another "proxy type" then it is not possible to do in web extension. It can only support what FF supports by itself: SOCKS5, SOCKS4, HTTP, HTTPS.
