### ISSUE TITLE
Add setting to allow proxifying localhost

### ISSUE THREAD

**Issue by dbeniamine** [bekh6ex/firefox-container-proxy#30]
First of all container proxy is awesome, and way more subtle than foxyproxy.

Sadly following #21 I had to switch back to foxyproxy. Indeed I use container proxy to acces services only available on localhost by sending  all trafic through a ssh tunnel.

Would it be possible to add a setting on the proxy configuration that let the user choose if localhost, 127.0.0.1 and :::1 are to be proxified or not.

This would replace #29.

**Comment by bekh6ex** [comment]
Let me try to clarify: you have another server where there is a service listening on 127.0.0.1. Also on that server there is a proxy running to which you set up in the extension in order to access service running locally (on that server).

Did I get it right? If not, can you explain?

**Comment by dbeniamine** [comment]
I have a server which has some services (docker) that are only accessible via 127.0.0.1 (blocked by firewall).

1. This connection is not possible : blocked by firewall
```
laptop --> server:8080
```
2. So I do a  tunnel `ssh -D <port> server`
```
laptop -->|ssh tunel| server --> localhost:8080
```
3. At the end of the day, on Firefox I go tho http://localhost:8080 with the proxy set to send all trafic to `<port>` including `localhost`
```
laptop -->|proxy| localhost:8080
```

**Comment by bekh6ex** [comment]
Oh! Didn't know you can do that!
Ok will fix ASAP, which is probably next week. 
If someone wants to crate a PR, you're more than welcome.

**Comment by bekh6ex** [comment]
That's been a long week 😄 
Sorry for that.
Please check version 0.1.15, should work.
If doesn't, please reopen the issue.

**Comment by dbeniamine** [comment]
It's perfect !

I just had to uncheck this setting on my proxies (screenshot in case it helps someone):

![image](https://user-images.githubusercontent.com/2989133/98957448-80247500-2501-11eb-8647-5485a72480e3.png)

thanks a lot for this feature !
