### ISSUE TITLE
Websites making large numbers of requests cause browser chrome to become unresponsive

### ISSUE THREAD

**Issue by as-com** [bekh6ex/firefox-container-proxy#34]
Steps to reproduce:
1) Create a container
2) Assign a proxy (I used an HTTPS proxy with username/password authentication)
3) Open speedtest.net (some other websites making a large number of requests do this as well)

Expected result:
The browser does not crash

Actual result:
Browser chrome becomes unresponsive, Firefox process consumes excessive CPU

Firefox versions: 84.0b8 (Developer Edition), 83.0
OS: Windows 10

**Comment by bekh6ex** [comment]
Sadly I couldn't reproduce the issue.

I don't have Windows, but on Mac in Firefox 84.0.2 speedtest.net works just fine, browser stays responsive, CPU usage of Firefox goes up (to 80-150%), but nothing critical. Also, Firefox Task manager (about:performance) shows that Container proxy add-on barely contributes to the load during the speed test as well as during the page load.

I need more input to continue investigating it. Are you sure that it is Container Proxy extension that makes chrome unresponsive? I am constantly using it for ~1,5 years with HTTPS proxies on Mac and Linux and I don't think I had an issue with unresponsive chrome. Can it be some another extension?

**Comment by as-com** [comment]
Hmm, it seems there's an issue with Firefox proxy extensions in general (or Firefox itself) and the specific proxy service I'm using. I'm going to keep digging.
