### ISSUE TITLE
Feature request: Wish there are options to add more container

### ISSUE THREAD

**Issue by NoToPro** [bekh6ex/firefox-container-proxy#35]
Thanks for this good plugin that makes my life become easy. 

But I find there is only limit container there.

Possible add options that can create more cotainers (just like the way that I create proxy) so that I can use more proxies.

**Comment by bekh6ex** [comment]
Containers is a Firefox feature. As soon as it is enabled (you installed at least one extension that works with containers) you can mannage them in menu: FIle -> New container tab -> Manage containers (direct link: about:preferences#containers )
