### ISSUE TITLE
The following error was encountered while trying to retrieve the URL: error:invalid-request

### ISSUE THREAD

**Issue by ptokponnon** [bekh6ex/firefox-container-proxy#36]
I installed and configure squid on a personnel server; it works, no doubt. checked it with fogldn and directly in firefox .
But when I add it in Container proxy, the test return 
`Error! Unable to connect to the proxy. The settings are probably incorrect.`
The wireshark trace reveals this 
`The following error was encountered while trying to retrieve the URL: error:invalid-request`
And I found this in the squid acces.log : 
`1607956453.065      0 xxx.xxx.xxx.xxx NONE/400 3740 NONE error:invalid-request - HIER_NONE/- text/html`
What am i missing?

**Comment by bekh6ex** [comment]
Hi!
Thanks for the report.
Can you post your full Squid config and version so I will try to reproduce.

Otherwise I don't know where to start digging.

**Comment by ptokponnon** [comment]
Please, find attached the config.
[squid.txt](https://github.com/bekh6ex/firefox-container-proxy/files/5712773/squid.txt)
Squid Cache: Version 4.10

**Comment by bekh6ex** [comment]
Sorry, couldn't reproduce.
I've managed to run it with your config (made just some small adjustments to fit my environment), but it works absolutely fine: correct credentials - it proxies, wrong credentials - it asks for the correct one.

I don't know what more can I do here. If you have suggestions, you are welcome.
