### ISSUE TITLE
Socks4 porxy not working

### ISSUE THREAD

**Issue by tonydream888** [bekh6ex/firefox-container-proxy#41]
Hello,

I have socks4 proxy that working when use firefox proxy setting but it is not working under this addon.

You can test socks 4 proxies on https://www.socks-proxy.net/

**Comment by bekh6ex** [comment]
Currently, the extension always sets `proxyDNS` flag for socks proxies.
Apparently, proxies from this site do not support proxying DNS requests, that's why they do not work. 

Someone (probably me ;) ) has to add 'proxy DNS' setting to the UI to make it configurable.

**Comment by bekh6ex** [comment]
See #42
