### ISSUE TITLE
Unable to connect to any Proxy (Socks4/5 or https [and http])

### ISSUE THREAD

**Issue by PaulGronwald** [bekh6ex/firefox-container-proxy#43]
Currently on Firefox version 92.0 the Proxy tests are unable to finish and the proxy cant be used.
Using free Proxy lists to search for Proxies without authentication I was able to find otherwise new and connectable Proxies.
Pic. 1 displays the error given back. (https proxy)

![awdawda](https://user-images.githubusercontent.com/38107523/132962479-0c699d63-e7a2-4376-bfa3-a29916d374d1.png)

Using the Firefox options to set up the exact same proxy works and even shows the Proxys IP on DuckDuckGo.

The Extensions has the needed authorization enabled (cookies and Proxy-Settings for firefox).

Also tried with Socks 4 and 5 but they had the same Problem

The same happend on Version 89.0 of Firefox with otherwise connectable Proxys

**Comment by bekh6ex** [comment]
Thank you for the report, but sadly with given amount of information I cannot give you any answer.
If the mentioned proxy is public, can you provide it's setting here so I can try to reproduce the issue?

**Comment by bekh6ex** [comment]
Might be fixable with disabling DNS proxying. 
I suggest to update to v0.1.21 and check

**Comment by bekh6ex** [comment]
There is also v 0.1.22 released that fixes some issues with HTTP proxies.
I will close this for now.
