### ISSUE TITLE
[enhancement] The latest features of Firefox 94, there may be a better solution?

### ISSUE THREAD

**Issue by Glide01** [bekh6ex/firefox-container-proxy#45]
https://www.mozilla.org/en-US/firefox/94.0/releasenotes/
> We’re rolling out the Firefox Multi-Account Containers extension with Mozilla VPN integration. This lets you use a different server location for each container.

Does this mean that there is official API support so that there is no need to use cookies to identify requests from containers?

Thanks.

**Comment by bekh6ex** [comment]
I didn't understand what do you mean when you say there is no need to use cookies.
Can you clarify a bit more?

**Comment by Glide01** [comment]
It's just that in the current version, for example, if I open a site in a container, not all requests go through the proxy and some escape. I've tried other container proxy plugins as well.
Now this new feature of Firefox 94, it may be different.

**Comment by bekh6ex** [comment]
I think there might be some misunderstanding.
It's not Firefox feature. They maintain [Firefox Multi-Account Containers extension](https://addons.mozilla.org/en-GB/firefox/addon/multi-account-containers/), and the feature is in the extension.

There might be some Firefox feature/integration with Mozilla VPN, but this is not directly applicable to Container Proxy extension and it's goals.
Putting in simple words: I don't have Mozilla VPN and cannot implement integration with it. Also, I don't see a reason, as soon as Mozilla did it.

Thank you for the issue and bringing it up, I totally missed it. This is relevant and interesting topic, but not really applicable.

Regarding request escaping I have a question: Does it happen in all other extensions as well? Or there are some that allow one to set proxy for container and requests do not escape?

**Comment by Glide01** [comment]
Sidebery
https://addons.mozilla.org/en-US/firefox/addon/sidebery/

Lightweight Container Proxy
https://addons.mozilla.org/en-US/firefox/addon/lightweight-container-proxy-02/

SmartProxy
https://addons.mozilla.org/en-US/firefox/addon/smartproxy/

I tried all of these plugins, and the result is that some requests will escape. For example, if I use Tor to access www.nytimes.com, these are the requests that will escape.
<img width="347" alt="image" src="https://user-images.githubusercontent.com/24718328/140549405-4ab44fa0-1c8a-4353-8eaf-05efc36bdac5.png">

So if I want all requests to go through Tor, I need to set up Tor for the Default container.
