### ISSUE TITLE
Version 0.1.19 breaks DNS forwarding

### ISSUE THREAD

**Issue by nvllsvm** [bekh6ex/firefox-container-proxy#47]
Firefox 94.0
Arch Linux
Firefox Multi-Account Containers 8.0.1

**With Container proxy 0.1.18**: DNS lookups are sent over configured SOCKS5 proxy
**With Container proxy 0.1.19**: DNS lookups are **not** sent over configured SOCKS5 proxy

Downgrading back to 0.1.18 lets things work again.

**Comment by bekh6ex** [comment]
Sorry, my mistake.
Version 0.1.19 is disabled, version 0.1.20 should not have this issue and is now available.
Please update and check if the issue is gone.
Thank you for the report

**Comment by nvllsvm** [comment]
0.1.20 resolves the issue, thanks!
