### ISSUE TITLE
Proxies not working suddenly?

### ISSUE THREAD

**Issue by best-of-blog** [bekh6ex/firefox-container-proxy#48]
Not sure if this is related to the update that just pushed, but my HTTP proxies are not working now. It's automatically using my direct connection.

(Speaking of automatically using direct connection, is there any way to make it so that doesn't happen?? I'd much prefer it to show an error rather than just bypass the proxy)

**Comment by bekh6ex** [comment]
Hm...
Couple of questions:
1. It's HTTP (not HTTPS), right?
2. Do you need some credentials to use it?

**Comment by bekh6ex** [comment]
Regarding error instead of bypass:
Totally agree.  I looked into it before and didn't find a clear way to do it, but something can be done.

**Comment by best-of-blog** [comment]
> Hm... Couple of questions:
> 
> 1. It's HTTP (not HTTPS), right?
> 2. Do you need some credentials to use it?

I have it set to HTTP, HTTPS has never worked. I’m connecting to HTTPS sites but up until apparently yesterday, this worked fine. My proxies have been the same for six months. If I use FoxyProxy with the same proxies, it works great. No credentials, it’s IP based auth.

**Comment by bekh6ex** [comment]
Just uploaded new version 0.1.22 that fixes a couple of issues with HTTP proxies that were recently introduced. It’s just got approved, so you can update.

**Comment by bekh6ex** [comment]
> If I use FoxyProxy with the same proxies, it works great.

@best-of-blog Is it setup as HTTP in FoxyProxy as well?

**Comment by best-of-blog** [comment]
> Just uploaded new version 0.1.22 that fixes a couple of issues with HTTP proxies that were recently introduced. It’s just got approved, so you can update.

Not sure what you did but it fixed the issue! Also, yes FoxyProxy uses HTTP. Thanks!

**Comment by dehghani-mehdi** [comment]
Same issue here, updating to `0.1.22` solved the problem.
