### ISSUE TITLE
How can I set both http and https proxy in one container?

### ISSUE THREAD

**Issue by tazihad** [bekh6ex/firefox-container-proxy#60]
Basically I use "green tunnel" to bypass govt ban on websites. Which requires I set https and http proxy to 127.0.0.1:8000. 
But as of now I can only set one.

**Comment by bekh6ex** [comment]
Hey.
I guess this is a common confusion around what HTTP proxy means.
In this case, when you specify HTTP proxy, it means that the proxy uses HTTP protocol to communicate with the client. Both http and https traffic will be forwarded to the proxy.
